package com.fly.dao;

import com.fly.domain.AppDevice;

import java.util.List;

public interface AppDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbg.generated
     */
    int insert(AppDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbg.generated
     */
    int insertSelective(AppDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbg.generated
     */
    AppDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AppDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_device
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppDevice record);

    /**
     * distince语法测试
     * @return
     */
    List<AppDevice> selectTestDistince();
}