package com.fly.domain;

import java.util.Date;

public class AppDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.lastLoginUserName
     *
     * @mbg.generated
     */
    private String lastloginusername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.createDate
     *
     * @mbg.generated
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.modifyDate
     *
     * @mbg.generated
     */
    private Date modifydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.bigVersion
     *
     * @mbg.generated
     */
    private String bigversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.projectType
     *
     * @mbg.generated
     */
    private Integer projecttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.deviceType
     *
     * @mbg.generated
     */
    private Integer devicetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_device.userName
     *
     * @mbg.generated
     */
    private String username;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.lastLoginUserName
     *
     * @return the value of app_device.lastLoginUserName
     *
     * @mbg.generated
     */
    public String getLastloginusername() {
        return lastloginusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.lastLoginUserName
     *
     * @param lastloginusername the value for app_device.lastLoginUserName
     *
     * @mbg.generated
     */
    public void setLastloginusername(String lastloginusername) {
        this.lastloginusername = lastloginusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.uuid
     *
     * @return the value of app_device.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.uuid
     *
     * @param uuid the value for app_device.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.token
     *
     * @return the value of app_device.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.token
     *
     * @param token the value for app_device.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.status
     *
     * @return the value of app_device.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.status
     *
     * @param status the value for app_device.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.createDate
     *
     * @return the value of app_device.createDate
     *
     * @mbg.generated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.createDate
     *
     * @param createdate the value for app_device.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.modifyDate
     *
     * @return the value of app_device.modifyDate
     *
     * @mbg.generated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.modifyDate
     *
     * @param modifydate the value for app_device.modifyDate
     *
     * @mbg.generated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.bigVersion
     *
     * @return the value of app_device.bigVersion
     *
     * @mbg.generated
     */
    public String getBigversion() {
        return bigversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.bigVersion
     *
     * @param bigversion the value for app_device.bigVersion
     *
     * @mbg.generated
     */
    public void setBigversion(String bigversion) {
        this.bigversion = bigversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.projectType
     *
     * @return the value of app_device.projectType
     *
     * @mbg.generated
     */
    public Integer getProjecttype() {
        return projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.projectType
     *
     * @param projecttype the value for app_device.projectType
     *
     * @mbg.generated
     */
    public void setProjecttype(Integer projecttype) {
        this.projecttype = projecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.deviceType
     *
     * @return the value of app_device.deviceType
     *
     * @mbg.generated
     */
    public Integer getDevicetype() {
        return devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.deviceType
     *
     * @param devicetype the value for app_device.deviceType
     *
     * @mbg.generated
     */
    public void setDevicetype(Integer devicetype) {
        this.devicetype = devicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_device.userName
     *
     * @return the value of app_device.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_device.userName
     *
     * @param username the value for app_device.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }
}