package com.fly.domain;

import java.util.Date;

public class PushMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.traceId
     *
     * @mbg.generated
     */
    private Long traceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.devicePlatform
     *
     * @mbg.generated
     */
    private String deviceplatform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.deviceToken
     *
     * @mbg.generated
     */
    private String devicetoken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.appVersion
     *
     * @mbg.generated
     */
    private String appversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.osVersion
     *
     * @mbg.generated
     */
    private String osversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.jobId
     *
     * @mbg.generated
     */
    private String jobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.sendTime
     *
     * @mbg.generated
     */
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.clickTime
     *
     * @mbg.generated
     */
    private Date clicktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column push_message.modifyTime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.id
     *
     * @return the value of push_message.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.id
     *
     * @param id the value for push_message.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.traceId
     *
     * @return the value of push_message.traceId
     *
     * @mbg.generated
     */
    public Long getTraceid() {
        return traceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.traceId
     *
     * @param traceid the value for push_message.traceId
     *
     * @mbg.generated
     */
    public void setTraceid(Long traceid) {
        this.traceid = traceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.devicePlatform
     *
     * @return the value of push_message.devicePlatform
     *
     * @mbg.generated
     */
    public String getDeviceplatform() {
        return deviceplatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.devicePlatform
     *
     * @param deviceplatform the value for push_message.devicePlatform
     *
     * @mbg.generated
     */
    public void setDeviceplatform(String deviceplatform) {
        this.deviceplatform = deviceplatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.deviceToken
     *
     * @return the value of push_message.deviceToken
     *
     * @mbg.generated
     */
    public String getDevicetoken() {
        return devicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.deviceToken
     *
     * @param devicetoken the value for push_message.deviceToken
     *
     * @mbg.generated
     */
    public void setDevicetoken(String devicetoken) {
        this.devicetoken = devicetoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.status
     *
     * @return the value of push_message.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.status
     *
     * @param status the value for push_message.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.userId
     *
     * @return the value of push_message.userId
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.userId
     *
     * @param userid the value for push_message.userId
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.appVersion
     *
     * @return the value of push_message.appVersion
     *
     * @mbg.generated
     */
    public String getAppversion() {
        return appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.appVersion
     *
     * @param appversion the value for push_message.appVersion
     *
     * @mbg.generated
     */
    public void setAppversion(String appversion) {
        this.appversion = appversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.osVersion
     *
     * @return the value of push_message.osVersion
     *
     * @mbg.generated
     */
    public String getOsversion() {
        return osversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.osVersion
     *
     * @param osversion the value for push_message.osVersion
     *
     * @mbg.generated
     */
    public void setOsversion(String osversion) {
        this.osversion = osversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.jobId
     *
     * @return the value of push_message.jobId
     *
     * @mbg.generated
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.jobId
     *
     * @param jobid the value for push_message.jobId
     *
     * @mbg.generated
     */
    public void setJobid(String jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.sendTime
     *
     * @return the value of push_message.sendTime
     *
     * @mbg.generated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.sendTime
     *
     * @param sendtime the value for push_message.sendTime
     *
     * @mbg.generated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.clickTime
     *
     * @return the value of push_message.clickTime
     *
     * @mbg.generated
     */
    public Date getClicktime() {
        return clicktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.clickTime
     *
     * @param clicktime the value for push_message.clickTime
     *
     * @mbg.generated
     */
    public void setClicktime(Date clicktime) {
        this.clicktime = clicktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.createTime
     *
     * @return the value of push_message.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.createTime
     *
     * @param createtime the value for push_message.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column push_message.modifyTime
     *
     * @return the value of push_message.modifyTime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column push_message.modifyTime
     *
     * @param modifytime the value for push_message.modifyTime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}